index:
  path: /
  controller: App\Controller\EventController::index

create-event:
  path: /create-event
  controller: App\Controller\EventController::new

show-events:
  path: /show-events
  controller: App\Controller\EventController::show

delete-event:
  path: /delete-event/{id}
  controller: App\Controller\EventController::delete

update-event:
  path: /update-event/{id}
  controller: App\Controller\EventController::edit

register:
  path: /register
  controller: App\Controller\AuthenticationController::register

app_login:
  path: /login
  controller: App\Controller\AuthenticationController::login

app_logout:
  path: /logout
  controller: App\Controller\AuthenticationController::logout
