index:
    path: /
    controller: App\Controller\EventController::index
    methods: GET

create-event:
    path: /create-event
    controller: App\Controller\EventController::new
    methods: GET|POST

show-events:
    path: /show-events
    controller: App\Controller\EventController::show
    methods: GET

delete-event:
    path: /delete-event/{id}
    controller: App\Controller\EventController::delete
    methods: DELETE

update-event:
    path: /update-event/{id}
    controller: App\Controller\EventController::edit
    methods: GET|POST
